const socialMediaGetString = {
  0: 'facebook',
  1: 'messenger',
  2: 'instagram',
  3: 'twitter',
  4: 'skype',
  5: 'linkedIn',
  6: 'whatsapp',
  7: 'tiktok',
  8: 'reddit',
  9: 'discord',
  10: 'pinterest',
  11: 'dribble',
  12: 'youtube',
  13: 'behance',
  14: 'telegram',
  15: 'tumblr',
  16: 'spotify',
  17: 'website',
};

const socialMediaGetNum = [
  'facebook',
  'messenger',
  'instagram',
  'twitter',
  'skype',
  'linkedIn',
  'whatsapp',
  'tiktok',
  'reddit',
  'discord',
  'pinterest',
  'dribble',
  'youtube',
  'behance',
  'telegram',
  'tumblr',
  'spotify',
  'website',
];

module.exports = {
  socialMediaGetString,
  socialMediaGetNum,
};
